### ISSUE TITLE
Question about persistent storage

### ISSUE THREAD

**Issue by mtompkins** [jimsihk/moodle-php-nginx#122]
Thanks for this image / work.

I'm trying to migrate to this project from Bitnami and have a question about your use of `nobody` and volumes. Specifically, Bitnami uses the convention of explicit mounts for volume persistence.

`- /path/to/moodle-persistence:/bitnami/moodle`

As I am trying to preserve the existing data, I'm attempting to map to your structure, however your use of implicit storage is making that a challenge. I have tried to adjust your `docker-compose` such that I do something like:

```
- ./moodledata:/var/www/moodledata
- ./moodlehtml:/var/www/html
```

with ownership of those folders as `nobody` (`65534`). When doing so, the container fails to startup.

I'd appreciate any insight you may be able to provide. 
I've tried a couple things:
- explicit `user`  in `docker-compose`
- `PUID` & `GUID` env variables
- adding :`rw` to the volume maps
- `chmod 777` on the voume folders as a debug effort

 but none of them allow the container to write to the mapped volume.
 
 Once I know I can get the container launched I can (hopefully) align the data movement.
 
 Many thanks!

**Comment by jimsihk** [comment]
Hi,

It is happy to know someone found it useful!

For persistent storage, due to the nature of `nobody`, we will need to change the owners of all the files of that existing storage to `nobody`, e.g. `chown -R nobody:nobody /var/www/moodledata`. For directories and files created by this image, it could be used properly.

But beware that the `/bitnami/moodle` may contains the moodle code which are not required to be mounted for this image.

Another workaround is to perform a file migration instead of mounting the existing disk to the container, this is actually what I used and found even easier if additional storage is allowed. For example,
1. ssh into the bitnami moodle container
2. create a tar ball on the moodledata
3. start up the new alpine-moodle container
4. ssh into the alpine-moodle container which should show you login as nobody
5. transfer the tar ball into the alpine-moodle container
6. untar the tar ball into `/var/www/moodledata`

In this way, the moodledata directories and files are all created under `nobody`

FYI if you are using k8s, this is what I added as an initContainer when mounting volumes managed externally like longhorn or openebs:
```
      initContainers:
      - name: set-folder-permission
        image: alpine
        command: ["chown"]
        args: ["nobody:nobody", "/var/www/moodledata"]
        volumeMounts:
          - mountPath: /var/www/moodledata
            name: moodle-data
            subPath: moodledata
```

**Comment by mtompkins** [comment]
Thank you for taking the time to respond. Also thank you for the migration suggestion. Unfortunately the Bitnami container is no longer functional (and one of the reasons I've looked for an alternative). I'm hoping they will resolve the PHP issue I have posted to their repo.

What you have provided generally, however, does not work in my testing with `docker compose`. Specifically, if you take your image and try to create persistent storage the container will fail to launch. To confirm please disregard any context I provided about migration and just try a standard persistent volume mount with `nobody` as I indicated earlier. You should be able to see it will not launch.

Essentially I had the same expectation as you have described, that paths with proper `nobody` ownership would suffice. It does not.

It is super interesting the `k8s` manages to work as expected.

**Comment by mtompkins** [comment]
Below is a simplified `docker-compose` that can be used to replicate what I am referencing:
Note the `data` folder is owned by `nobody:nobody`
```
[root@dpw1 test]# ls -lha
total 4.0K
drwxr-xr-x 1 root   root     44 May 24 19:58 .
drwx------ 1 root   root    414 May 24 19:40 ..
drwxr-xr-x 1 nobody nobody   40 May 24 19:55 data
-rw-r--r-- 1 root   root   1.3K May 24 19:58 docker-compose.yml
[root@dpw1 test]# id nobody
uid=65534(nobody) gid=65534(nobody) groups=65534(nobody)
```
`docker-compose.yml`
```
version: '3'

services:
  postgres-moodle:
    container_name: postres-moodle
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=moodle
      - POSTGRES_USER=moodle
      - POSTGRES_DB=moodle
    volumes:
      - postgres:/var/lib/postgresql/data

  moodle:
    container_name: "moodle"
    image: jimsihk/alpine-moodle
#    command: tail -F anything
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:8080
    depends_on:
      - postgres-moodle
    volumes:
      - ./data/moodledata:/var/www/moodledata
      - ./data/moodlehtml:/var/www/html
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - SITE_URL=http://localhost
      - DB_TYPE=pgsql
      - DB_HOST=postgres-moodle
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
      - SSLPROXY=false
      - MOODLE_EMAIL=user@example.com
      - MOODLE_LANGUAGE=en
      - MOODLE_SITENAME=Moodle
      - MOODLE_USERNAME=moodleuser
      - MOODLE_PASSWORD=randomPassword
      - MOODLE_MAIL_NOREPLY_ADDRESS=noreply@localhost
      - MOODLE_MAIL_PREFIX=[moodle]
      - AUTO_UPDATE_MOODLE=true

volumes:
  postgres: null
```

Which produces the following failure as indicated:
```
postres-moodle  | 2023-05-24 23:57:03.005 UTC [24] LOG:  database system was shut down at 2023-05-24 23:56:29 UTC
postres-moodle  | 2023-05-24 23:57:03.007 UTC [1] LOG:  database system is ready to accept connections
moodle          | Starting startup scripts in /docker-entrypoint-init.d ...
moodle          | *** Running: /docker-entrypoint-init.d/01-uname.sh
moodle          | Linux 05ef646fe511 6.1.29-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 17 May 2023 11:35:20 +0000 x86_64 Linux
moodle          | *** Running: /docker-entrypoint-init.d/02-configure-moodle.sh
moodle          | Waiting for postgres-moodle:5432 to be ready
moodle          | postgres-moodle is ready
moodle          | Generating config.php file...
moodle          | PHP Warning:  Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
moodle          | Could not open input file: /var/www/html/admin/cli/install.php
moodle          | *** Failed with return value: 0
moodle          | Finished startup scripts in /docker-entrypoint-init.d
moodle          | Starting runit...
moodle          | Started runsvdir, PID is 14
moodle          | wait for processes to start....
moodle          | /usr/sbin/crond 4.5 dillon's cron daemon, started with loglevel notice
moodle          | [24-May-2023 23:57:06] NOTICE: fpm is running, pid 20
moodle          | [24-May-2023 23:57:06] NOTICE: ready to handle connections
moodle          | run: cron: (pid 19) 5s
moodle          | run: nginx: (pid 18) 5s
moodle          | run: php: (pid 20) 5s
moodle          | initgroups failed: nobody Operation not permitted
moodle          | unable to ChangeUser (user nobody /usr/bin/php  /var/www/html/admin/cli/cron.php > /dev/null)
moodle          | exit status 1 from user nobody /usr/bin/php  /var/www/html/admin/cli/cron.php > /dev/null
```
